theme = "from_mocha"

[editor]
cursor-shape = { insert = "bar", normal = "block", select = "underline" }
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
