inherits = "catppuccin_mocha"
"ui.background" = {}
"ui.virtual.inlay-hint" = { fg = "#7f849c" }
"ui.virtual.inlay-hint.type" = { fg = "#7f849c" }
"ui.virtual.inlay-hint.parameter" = { fg = "#7f849c" }
